---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-0423
    - profile-0423
    - user-0423
    - webserver-0423

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"